[package]
name = "grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
dash-common = { path = "../common" }
embeddings = { path = "../../pkg/embeddings" }

serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { version = "0.12", features = ["server"] }
prost = { version = "0.13" }
tracing = { workspace = true }

[build-dependencies]
tonic-build = { version = "0.12" }
